# Generated by Django 3.2 on 2021-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_image_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
